description: "Cow device handler"
services:
  generic:
    uuid: "0000cd00-caa9-44b2-8b43-96ae3072fd3"
    characteristics:
      led:
        uuid: "0000cd01-caa9-44b2-8b43-96ae3072fd36"
        flags: ["-l", "--led"]
        type: "number"
        choices: [0, 1]
        help: "switch device's led state: 0 -- off, 1 -- on"
        password_protected: false

      time:
        uuid: "0000cd02-caa9-44b2-8b43-96ae3072fd36"
        flags: ["-t", "--time"]
        type: "string"
        help: "set device's time, format: HH/MM/SS with leading zero's"

      date:
        uuid: "0000cd03-caa9-44b2-8b43-96ae3072fd36"
        flags: ["-d", "--date"]
        type: "string"
        help: "set device's date, format: DD/MM/YY with leading zero's. YY >= 18"

      tx_power:
        uuid: "0000cd04-caa9-44b2-8b43-96ae3072fd36"
        flags: ["-p", "--txpower"]
        type: "number"
        choices: [4, 3, 0, -4, -8, -12, -16, -20, -40]
        help: "set device's TxPower in dBm"

      adv_interval:
        uuid: "0000cd05-caa9-44b2-8b43-96ae3072fd36"
        flags: ["-a", "--adv_interval2"]
        type: "number"
        length: 2
        order: "little"
        help: "set device's adv_interval in ms, min 250, max 10240"

      switch:
        uuid: "0000cd06-caa9-44b2-8b43-96ae3072fd36"
        flags: ["-s", "--switch"]
        type: number
        choices: [0, 1, 2]
        help: "switch device's state: 0 -- off, 1 -- normal mode, 2 -- allways run"

    special:
      error:
        uuid: "0000cd07-caa9-44b2-8b43-96ae3072fd36"
      password:
        uuid: "0000cd08-caa9-44b2-8b43-96ae3072fd36"
